name : spotless

on : push

jobs :
  spotlessCheck :
    runs-on : ubuntu-latest
    timeout-minutes : 10

    steps :
      - name : Checkout
        uses : actions/checkout@v2

      - name : Validate Gradle Wrapper
        uses : gradle/wrapper-validation-action@v1

      - name : Configure JDK
        uses : actions/setup-java@v1
        with :
          java-version : '11.0.4'

      - name : spotless
        run : ./gradlew spotlessCheck
